version: "3.9"

services:
  metabase:
    image: metabase/metabase:${METABASE_TAG}
    container_name: ${PROJECT_NAME}-metabase
    hostname: metabase
    restart: unless-stopped
    stop_grace_period: 10s
    env_file: .env
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: postgres
      MB_DB_PORT: 5432
      MB_DB_PASS: $DB_PASSWORD
      MB_DB_DBNAME: $DB_NAME
      MB_DB_USER: $DB_USER
      MB_DB_FILE: /metabase-data/metabase.db
    ports:
      - ${METABASE_PORT}:3000
    volumes:
      - metabase-data:/metabase-data

  postgres:
    image: postgres:${POSTGRES_TAG}
    container_name: ${PROJECT_NAME}-postgres
    hostname: postgres
    restart: unless-stopped
    stop_grace_period: 10s
    env_file: .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:${ADMINER_TAG}
    container_name: ${PROJECT_NAME}-adminer
    hostname: adminer
    restart: unless-stopped
    stop_grace_period: 10s
    env_file: .env
    ports:
      - ${ADMINER_PORT}:8080

networks:
  default:
    name: $PROJECT_NAME
    driver: bridge

volumes:
  postgres-data: {}
  metabase-data: {}
